name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  #----------------------------------- code-quality -----------------------------------#

  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry==1.4.0
      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: poetry install --with lint
      - name: Run lint
        run: |
          poetry run ruff .

  #-------------------------------------- tests ---------------------------------------#

  tests:
    needs: code-quality

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: pipx install poetry==1.4.0
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: poetry install --with test
      - name: Run tests
        run: poetry run pytest
